class ResumeKeys:
    def StopKeys():
        return[
        "volunteer experience",
        "AREAS OF EXPERTISE".lower(),
        "technical proficiency",
        'techincal experience',
        "achievements",
        'career goal',
       'resume summary',
        'objective',
        "expertise",
        "successfull aquisitions",
        "personal achievements"
        "PERSONAL PROFILE".lower(),
        "professional profile",
        "competencies",
        "accomplishments",
        "core qualifications",
        "certifications and memberships",
        "certifications & memberships",
        "UNIVERSITY GRADUATE".lower(),
        "CORE COMPETENCIES AND ACHIEVEMENTS".lower(),
        'career objective',
        'employment objective',
        "PROFESSIONAL QUALIFICATION".lower(),
        "PROJECT DETAILS".lower(),
        "PROFESSIONAL EXPERIENCE".lower(),
        "projects",
        "INTERPERSONAL SKILLS".lower(),
        "ineterests",
        "PROJECT PROFILE".lower(),
        "projects information",
        "projects info",
        'employment details',
        "employment experience",
        "career experience",
        'professional objective',        
        'career summary',
        'professional summary',
        'summary of qualifications',
        'summary',
        "STRENGTH".lower(),
        "strengths",
        "organizations",
        "immigration",
        "immigration status","immigration info","immigration information",
        'career profile',
        'employment history',
        'work history',
        'work experience',
        "executive summary",
        'experience',
        "objective",
        "passions",
        "languages",
        "career objective",
        'professional experience',
        'professional background',
        'additional experience',
        'freelance experience',
        'army experience',
        "hobbies and interests",
        "hobbies & interests",
        "programing languages",
        'military experience',
        'career related experience',
        'related experience',
        'programming experience',
        'freelance',
        "foreign languages",
        "Presentation Skills".lower(),
        "languages known",
        "Companies worked at".lower(),
        "Senior Leadership Skills".lower(),
        'military background',
        'academic background',
        'academic experience',
        'courses',
        'related courses',
        'education',
        
        "publications",
        "education background",
        "EDUCATIONAL SUMMARY".lower(),
        "education information",
        "education details",
        "education",
        'educational background',
        "EDUCATIONAL AND PUBLICATION CERTIFICATION".lower(),
        "EDUCATIONAL & PUBLICATION CERTIFICATION".lower(),

        "education certification",
        "education certifications",
        "education and certification",
        "education and certifications",
        'educational qualifications',
        'educational and qualifications',
        "educational qualification",
        "educational and qualification",
        'qualifications',
        "profile summary",
        "references",
        "Work Preferences".lower(),
        "Preferences".lower(),
        "Work Preferences".lower(),
        "Preferences".lower(),
        "Work Priority".lower(),
        "Priority".lower(),
        "conferences",
        "Profile Sources".lower(),
        "Contact Information".lower(),
        "contact",
        "profile",
        "about me",
        "about myself",
        "my contact",
        "Work History".lower(),
        "EDUCATIONAL PUBLICATION & CERTIFICATION".lower(),
        "PERSONAL DOSSIER".lower(),
        "PERSONAL information".lower(),
        "personal info",
        "about",
        "Passport Available".lower(),
        "passport status",
        "passport",
        "passport information",
        "passport info",
        "Languages known".lower(),
        "known languages",
        "Declaration".lower(),
        "visa available",
        "visa status",
        "Certifications and Licenses".lower(),
        "Certifications & Licenses".lower(),
        "additional activities",
        "visa",
        "visa info",
        "visa information",
        'educational training',
        'education and training',
        'education & training',
        "education details",
        'training',
        'academic training',
        'professional training',
        'course project experience',
        'related course projects',
        'internship experience',
        'internships',
        'apprenticeships',
        'college activities',
        'certifications',"my life philosophy",
        "certifications and training",
        'special training',

        "awards recieved"
        "contact me",
        'areas of experience',
        "relavant experience",
        'areas of knowledge',
    
        "other abilities",
        
        "personal details",
        'technical experience',
        'proficiencies',
        'languages',
      
        'programming languages',
        "AWARDS".lower()
        ]

