class resume_keys:
    def all_keys():
        return[
        "technical proficiency",
        'techincal experience',
        "achievements",
        'career goal',
        'objective',
        "professional profile",
        "areas of expertise",
        "ROLES AND RESPONSIBILITIES".lower(),
        "competencies",
        "ROLES".lower(),
        "RESPONSIBILITIES".lower(),
        'career objective',
        'employment objective',
        "Responsibilities".lower(),
        "PROFESSIONAL QUALIFICATION".lower(),
        "PROJECT DETAILS".lower(),
        "PROFESSIONAL EXPERIENCE".lower(),
        "projects",
        "PROJECT PROFILE".lower(),
        "PROFESSIONAL SUMMARY".lower(),
        "projects information",
        "projects info",
        'employment details',
        "employment experience",
        'professional objective',        
        'career summary',
        'professional summary',
        'summary of qualifications',
        'summary',
        "immigration",
        "immigration status","immigration info","immigration information",
        'career profile',
        'employment history',
        'work history',
        'work experience',
        "executive summary",
        'experience',
        'professional experience',
        'professional background',
        'additional experience',
        'freelance experience',
        'army experience',
        'military experience',
        'career related experience',
        'related experience',
        'programming experience',
        'freelance',
        "Companies worked at".lower(),
        
        'military background',
        "email_id",
        "email",
        "e mail",
        'academic background',
        'academic experience',
        'programs',
        'courses',
        'related courses',
        'education',
        'cell',
        "cell no",
        "cell_no",
        "mobile no",
        "COMPETENCIES".lower(),
        
        "EDUCATIONAL SUMMARY".lower(),
        "education information",
        "education details",
        "education",
        'educational background',
        "EDUCATIONAL PUBLICATION CERTIFICATION".lower(),
        "EDUCATIONAL PUBLICATION CERTIFICATIONS".lower(),
        "education certification",
        "education certifications",
        "education and certification",
        "education and certifications",
        'educational qualifications',
        'educational and qualifications',
        "educational qualification",
        "educational and qualification",
        'qualifications',
        
        "Work Preferences".lower(),
        "Preferences".lower(),
        "Work Preferences".lower(),
        "Preferences".lower(),
        "Work Priority".lower(),
        "Priority".lower(),
        "Profile Sources".lower(),
        "Contact Information".lower(),
        "contact",
        "Work History".lower(),
        
        "PERSONAL DOSSIER".lower(),
        "PERSONAL information",
        "e-mail",
        "mobile",
        "mobile number",
        "Passport Available".lower(),
        "passport status",
        "passport","passport information",
        "passport info",
        "Languages known".lower(),
        "known languages",
        "known languages",
        "Declaration".lower(),
        "Marital Status".lower(),
        "visa available",
        "visa status",
        "visa","visa info","visa information",
        "Achievements".lower(),
        'educational training',
        'education and training',
        "education details",
        'training',"adress",
        'academic training',
        'professional training',
        'course project experience',
        'related course projects',
        'internship experience',
        'internships',
        'apprenticeships',
        'college activities',
        'certifications',
        "certifications and training",
        'special training',
        'credentials',
        'areas of experience',
        'areas of expertise',
        'areas of knowledge',
        'skills',
        "other skills",
        "other abilities",
        'career related skills',
        'professional skills',
        'specialized skills',
        'technical skills',
        'computer skills',
        'personal skills',
        "personal details",
        'computer knowledge',        
        'technologies',
        'technical experience',
        'proficiencies',
        'languages',
        'language competencies and skills',
        'programming languages',
        'competencies',
        "AWARDS".lower()
        ]

